#!/usr/bin/python2
#coding=utf-8
import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/12.0 (Android; Opera Mini/52.2.2254/85. U; id) Presto/2.12.423 Version/12.16')]

def exb():
    print '[!] Exit Successful'
    os.sys.exit()

def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(3.0 / 200)

##### LICENSE #####
#=================#
def lisensi():
    os.system('clear')
    login()
####login#########
def login():
    os.system('clear')
    print 
    print
    jalan('\x1b[1;97mDo you want to continue? [y/n]  )')
    print
    print
    pilih_Somi()
    
def pilih_Somi():    
    Somi = raw_input("\n\033[1;97m>\033[1;93m")
    if Somi =="":
        print "\x1b[1;97mWRONG "
        pilih_Somi()
    elif Somi =="y":
    	os.system("rm -rf $HOME/WORLD")
        os.system("cd $HOME && git clone https://github.com/Somi190/WORLD.git")     
        
        time.sleep(5)
        os.system("cd $HOME/WORLD && python2 WORLD.py")
 
    elif Somi =="n":
    	exb()
    raw_input("\n\033[1;92m[\033[1;92mBack\033[1;95m]")
    login() 
          
if __name__ == '__main__':
    login()

